#pragma once

#ifndef NDEBUG

#define XR_ENABLE_RUNTIME_DEBUG 1
#define XR_ENABLE_DEBUG_REPORT_LOGGING 1
#define XR_ENABLE_DEBUG_REPORT_VERBOSE_BIT (XR_ENABLE_DEBUG_REPORT_LOGGING & 1)
#define XR_ENABLE_DEBUG_REPORT_INFORMATION_BIT (XR_ENABLE_DEBUG_REPORT_LOGGING & 1)
#define XR_ENABLE_FPS 1

#else

#define XR_ENABLE_RUNTIME_DEBUG 0
#define XR_ENABLE_DEBUG_REPORT_LOGGING 0
#define XR_ENABLE_DEBUG_REPORT_VERBOSE_BIT 0
#define XR_ENABLE_DEBUG_REPORT_INFORMATION_BIT 0
#define XR_ENABLE_FPS 0

#endif
