#pragma once

#define ENABLE_RUNTIME_DEBUG (DEBUG & 1)
#define ENABLE_DEBUG_REPORT_LOGGING (DEBUG & 1)
#define ENABLE_DEBUG_REPORT_INFORMATION_BIT (ENABLE_DEBUG_REPORT_LOGGING & 1)
#define ENABLE_DEBUG_REPORT_WARNING_BIT (ENABLE_DEBUG_REPORT_LOGGING & 1)
#define ENABLE_DEBUG_REPORT_DEBUG_BIT (ENABLE_DEBUG_REPORT_LOGGING & 1)
