#pragma once

#define ENABLE_DEBUG 1
#define ENABLE_RUNTIME_DEBUG (ENABLE_DEBUG & 1)
#define ENABLE_DEBUG_REPORT_LOGGING (ENABLE_DEBUG & 1)
#define ENABLE_DEBUG_REPORT_INFORMATION_BIT (ENABLE_DEBUG_REPORT_LOGGING & 1)
#define ENABLE_DEBUG_REPORT_WARNING_BIT (ENABLE_DEBUG_REPORT_LOGGING & 1)
#define ENABLE_DEBUG_REPORT_DEBUG_BIT (ENABLE_DEBUG_REPORT_LOGGING & 1)
#define ENABLE_FPS 1
